servicesDirPath: "~/.local/share/iac/services"
backupsDirPath: "~/.local/share/iac/backups"
envDirPath: "~/.local/share/iac/env"
kcvPath: "~/.local/share/iac/kcv.json"
masterKeyPath: "~/.local/share/iac/master_key"
